# permissions for end users to view freshrsses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freshrss-viewer-role
rules:
- apiGroups:
  - freshrss.demo.openshift.com
  resources:
  - freshrsses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freshrss.demo.openshift.com
  resources:
  - freshrsses/status
  verbs:
  - get
