# permissions for end users to edit freshrsses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freshrss-editor-role
rules:
- apiGroups:
  - freshrss.demo.openshift.com
  resources:
  - freshrsses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freshrss.demo.openshift.com
  resources:
  - freshrsses/status
  verbs:
  - get
